### ISSUE TITLE
socketio怎么使用？

### ISSUE THREAD

**Issue by lovesix1314** [c-kzxvldkhX/receiptnotice#107]
是不是开启之后程序每隔一段时间(自己设定的间隔时间)就去post一次服务器？然后那个 socket.io路由是固定不能改的吗？

**Comment by WeihuaGu** [comment]
它是保持一个连接，具体可以看wiki

**Comment by lovesix1314** [comment]
好的！

**Comment by lovesix1314** [comment]
一部手机发起了两个连接，怎么解决啊

**Comment by WeihuaGu** [comment]
没看懂，具体说下怎么发起的两个连接

**Comment by lovesix1314** [comment]
`package main

import (
	"fmt"
	"log"
	"net/http"

	socketio "github.com/googollee/go-socket.io"
)

func main() {
	server, err := socketio.NewServer(nil)
	if err != nil {
		log.Fatal(err)
	}

	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		return nil
	})

	server.OnEvent("/", "echo", func(s socketio.Conn, msg string) {
		fmt.Println("echo:", msg)
	})

	server.OnError("/", func(s socketio.Conn, e error) {
		fmt.Println("meet error:", e.Error())
	})

	server.OnDisconnect("/", func(s socketio.Conn, reason string) {
		fmt.Println("closed", reason)
	})

	go server.Serve()
	defer server.Close()

	http.Handle("/socket.io/", server)
	http.Handle("/", http.FileServer(http.Dir("./asset")))
	log.Println("Serving at localhost:8000...")
	log.Fatal(http.ListenAndServe(":8000", nil))
}
`

这是go 的代码
安卓客户端的间隔设置是20s
当服务端运行后，等待一会，app建立连接，正常发送心跳数据，但是过了一会，在第一个连接没有断开的情况下，app会再次建立一个新的链接，

另外，麻烦发布新版本的时候顺便发布编译好的app，不然向我这样的用户没有编译环境不太方便，谢谢啦！！！

**Comment by WeihuaGu** [comment]
这个不管几个连接，只是用来确定是否在线。我是用三个单例连接，如果没记错的话。会一定间隔发起新的连接

**Comment by lovesix1314** [comment]
好的，感谢！
