### ISSUE TITLE
建议直接放上打包好的apk,不知道怎么编译

### ISSUE THREAD

**Issue by xmwenfeng** [c-kzxvldkhX/receiptnotice#122]
请大神指教

**Comment by xmwenfeng** [comment]
帮忙编译个最新版吧 谢谢了

**Comment by WeihuaGu** [comment]
Action里应该直接可以下载最新的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: xmwenfeng<mailto:notifications@github.com>
发送时间: 2021年3月6日 22:25
收件人: c-kzxvldkhX/receiptnotice<mailto:receiptnotice@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [c-kzxvldkhX/receiptnotice] 建议直接放上打包好的apk,不知道怎么编译 (#122)


帮忙编译个最新版吧 谢谢了

―
