### ISSUE TITLE
报病毒：Android.merchant.n[prv.gen]

### ISSUE THREAD

**Issue by kenweini** [c-kzxvldkhX/receiptnotice#125]
这个软件给我带来了很大的方便，首先谢谢作者！

但最近，我发现在华为鸿蒙系统上报病毒：**Android.merchant.n[prv.gen]**
特别注：在安卓系统上没有报这个提示（我一直在安卓系统上用了2年了）。

这个是误报吗？需要理会它吗？如果不理会，总感觉不舒服！

如果不是误报，需要做处理吗？应该怎么处理？

谢谢！

![fengxian](https://user-images.githubusercontent.com/19920902/161007875-f76592b1-d426-4909-8d74-2a9d4837372c.png)

**Comment by WeihuaGu** [comment]
可能没有太好的办法。应用为了获得支付宝的转账金额，和一些信息，必须监控通知栏和使用无障碍服务。无障碍服务可以获得当前页面上的字符串信息。所以它提示有隐私泄露风险。
但是应用对使用者来说是完全无风险的，因为代码开源，你可以看到无障碍相关功能的源码。所以只要是github action 里下载的就没问题。
我没用过鸿蒙，不知道有没有白名单一类的，可以让它不报病毒。

**Comment by kenweini** [comment]
谢谢您的回复，这下我就放心了，再次感谢！
