### ISSUE TITLE
为什么不提供 1.[4 版本的 apk 啊？

### ISSUE THREAD

**Issue by GHTockey** [c-kzxvldkhX/receiptnotice#126]
下载的 1 压缩包用命令 gradlew assembleRelease 报错 “找不到key.properties”文件？
1.4 又报错 Task 'assembleRelease' not found in root project 'receiptnotice-master'.？
使用 Android Studio 构建又报错储存库使用了不安全的协议？我都服了

**Comment by WeihuaGu** [comment]
Actions里能生成后,就不在Releases里发布了.

那个报找不到key.properties”文件的,应该下载的是release分支,那个是我用来发布的,所以key.properties是我的签名文件,应该用master分支就没有了.

用assembleDebug,不用assembleRelease,因为你要release那个应该要签名的吧.

**Comment by GHTockey** [comment]
> 用assembleDebug,不用assembleRelease,因为你要release那个应该要签名的吧.

我使用 gradlew assembleDebug 命令依然报错 "* What went wrong:
Task 'assembleDebug' not found in root project 'receiptnotice'."

**Comment by WeihuaGu** [comment]
./gradlew build 呢？

**Comment by WeihuaGu** [comment]
./gradlew app:assembleDebug

**Comment by GHTockey** [comment]
> ./gradlew build 呢？

使用这个命令报错 "* What went wrong:
A problem was found with the configuration of task ':app:lint'.
> No value has been specified for property 'lintClassPath'."

> ./gradlew app:assembleDebug

这个报错 "Task 'assembleDebug' not found in project ':app'."

您把源码下载到电脑可以正常构建吗？可以的话或许是我的问题

**Comment by GHTockey** [comment]
主要是 0.7 的版本 socket 推送有问题，它断开后重连不上，必须将进程强制结束后再打开APP才可以推送。如果期间断开的话又会重复刚刚的问题

**Comment by WeihuaGu** [comment]
我也三年没动java和gradle了，你要是想自己构建，可以看看gradle的文档，会事半功倍。我可以随便git push一次提交，github就会自动构建新的apk

**Comment by GHTockey** [comment]
那麻烦你提交一下了

**Comment by WeihuaGu** [comment]
github Actions已经构建完成，并且可以下载了。
