### ISSUE TITLE
MD5该怎么使用

### ISSUE THREAD

**Issue by jamca012** [c-kzxvldkhX/receiptnotice#86]
D/ 03-18 21:22:51.946 NLService( 9830): md5 string: type is alipay price is 1.11   md5str:EF720324AE49B89C6F3141868749D355
D/ 03-18 21:22:51.948 NLService( 9830): 加密方法md5
D/ 03-18 21:22:51.948 NLService( 9830): 加密秘钥E7D5048276804F
D/ 03-18 21:22:51.970 NLService( 9830): post task postjson:{"money":"1.11","sign":"18BC241FF5D6786668304212D8DF9524","time":"2020-03-18 21:22:51","type":"alipay","title":"支付宝支付","deviceid":"10097","content":"L通过扫码向你付款1.11元"}

md5加密方法为md5(md5(1.11 + alipay) + E7D5048276804F)

这种该怎么使用解密呢。按照这个加密方法md5出来的不一样

**Comment by WeihuaGu** [comment]
是md5(md5(type+price) + secretkey)也就是说你把price+type改成type+price试下
```
public String getSignMd5WithSecretkey(String type, String price, String secretkey) {
        
        String md5str=getMd5String(getMd5String(type+price)+secretkey);
        return md5str;
    }
```

**Comment by jamca012** [comment]
md5(type+price)  
md5(alipay+1.11)=348a01218fa569369405cb990a81746e
但上面生成的是EF720324AE49B89C6F3141868749D355   
这个type+price里面是怎么排序的呢？

**Comment by jamca012** [comment]
是不是存在java生成的MD5跟PHP生成的不一致？

**Comment by WeihuaGu** [comment]
不加密钥的试下，看正常不

**Comment by jamca012** [comment]
测试去掉双层MD5以后就正常了  跟PHP后端一致。但当金额为null时 后台匹配的MD5又不一致了
