### ISSUE TITLE
在凌晨收到的几条到账信息没有推送

### ISSUE THREAD

**Issue by anotherDoctorXiong** [c-kzxvldkhX/receiptnotice#91]
凌晨支付宝和微信没有收款消息的通知栏信息，是否有人碰到一样的情况，这种情况一般是手机系统自身的问题还是支付宝自身的智能设置

**Comment by lshile** [comment]
我也遇到这种问题！凌晨4点后到8点这个时间段没有推送

**Comment by WeihuaGu** [comment]
只能找个另外的手机测试了……
