### ISSUE TITLE
支付宝完全不能推送了，LOG里面有支付宝通知记录，就是不能推送？！

### ISSUE THREAD

**Issue by RussiaVk** [c-kzxvldkhX/receiptnotice#93]
这是什么原因呢？？？

**Comment by sportgirl45** [comment]
支付宝通知title变了，不被app识别为支付通知，所以就收不到通知了。请看历史讨论帖。

**Comment by RussiaVk** [comment]
> 支付宝通知title变了，不被app识别为支付通知，所以就收不到通知了。请看历史讨论帖。

修复了吗，怎么解决呢

**Comment by WeihuaGu** [comment]
使用action里自动编译的试一试

**Comment by longhuan1999** [comment]
> 使用action里自动编译的试一试

又不行了
