### ISSUE TITLE
支付宝通知监控失效

### ISSUE THREAD

**Issue by careylipu** [c-kzxvldkhX/receiptnotice#97]
手机型号 redmi k30 5g
app版本 last
支付宝版本 10.1.90
标题 收钱码到账通知
内容 成功收款0.01元。享免费提现等更多专属服务，点击查看

详细信息：

Bundle[{android.title=收钱码到账通知, android.reduced.images=true, android.text=成功收款0.01元。享免费提现等更多专属服务，点击查看, android.appInfo=ApplicationInfo{6668dfd com.eg.android.AlipayGphone}, android.showWhen=true, android.largeIcon=Icon(typ=BITMAP size=99x99)}

**Comment by careylipu** [comment]
手机型号 oppo r15
app版本 last
支付宝版本 10.1.90
标题 收款通知
内容 X通过扫码向你付款0.01元


详细信息：

Bundle[{android.title=收款通知, android.reduced.images=true, android.icon=2130837513, android.text=X通过扫码向你付款0.01元, android.appInfo=ApplicationInfo{faf1f29 com.eg.android.AlipayGphone}, android.showWhen=true, android.largeIcon=android.graphics.Bitmap@bc4f2ae}]

**Comment by careylipu** [comment]
总结反馈：两部手机支付宝app版本一样，通知信息却不一样，两部手机支付宝监控均失效。监控推送app也是最新版，看了github代码按道理监控oppo r15那台应该已经适配，但是都不行。

**Comment by kuke21** [comment]
之前有人解答了 你翻翻看能找到答案！

**Comment by careylipu** [comment]
我知道了，发布的1.4不是最新的，最新的1.5没有发布出来，已经自己编译1.5版本。
